### ISSUE TITLE
Style language switcher block

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#39]
I placed this in the header as part of #38. By default, the Language Switcher block provides text for "English" and "Spanish". Not sure where we can fit that on the header but there seems to be some free space up there.

**Comment by kostajh** [comment]
Even though there's not a ton of translation yet, we'd like to show that it's at least in progress.

**Comment by AnneTee** [comment]
@kostajh How do I get this block to show up in the header?

**Comment by kostajh** [comment]
@AnneTee Good question. I see it listed in the "Header" section here (https://www.durhamatletico.com/admin/structure/block) but don't see any output.

**Comment by AnneTee** [comment]
This is proving tricky:

- The current language should have an `is-active` which opens up a lot of styling options (hiding the active language and only displaying other options, or at least obscuring the current langauge). However when I click on Español both links get an active class so it's useless.
- It looks like a dropdown is the most popular method for toggling languages. There's a module for that but the 8.x branch is 2 years old and isn't working out of the box.

I'll need to spend some more time on this one to get it looking good. @kostajh if you need these links to display sooner rather than later, I can just display the menu in a way that looks good enough for now and come back to it when I have more time.

**Comment by kostajh** [comment]
@AnneTee hah. When I click on Spanish, English remains with `is-active` and Spanish doesn't get an `is-active` class.

**Comment by kostajh** [comment]
@AnneTee in `page.html.twig`,
