### ISSUE TITLE
Add sponsors region to footer

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#56]
We need a way to display sponsors on the homepage/subpages. http://nchsaa.org/ can be a good guide for us, as the homepage template shows a way of displaying three tiers of sponsors. I think we'll probably end up with three tiers of sponsors but @davidfellerath could clarify.  /cc @AnneTee

**Comment by davidfellerath** [comment]
We have five tiers of sponsorship, but we are unlikely to require the top tier. I'm attaching our sponsor deck. In the third tier is JD Service Now, our biggest sponsor so far, and I would certainly want this business to be featured prominently. Right now there is only one active candidate for the second tier, but it is unconfirmed.
[Final DA Sponsor deck.pdf](https://github.com/durhamatletico/durhamatletico-cms/files/39137/Final.DA.Sponsor.deck.pdf)

**Comment by AnneTee** [comment]
This is getting there.

@kostajh After playing around with some options I'd suggest not adding sponsors to the footer unless you intend for them to be visible on every page. I'd expect the footer to look the same on all pages, and it seems strange in practice to put the bottom tier of sponsors in the footer on the frontpage but nowhere else, then higher tiers outside the footer on the front page.

Also writing myself a reminder to take another look at the linked images since this isn't working yet.

**Comment by kostajh** [comment]
@AnneTee I think this is all set but it looks like the link settings in the View got lost. If it's easy for you to recreate them in production, I can handle exporting & committing. Otherwise I can get to that later.

**Comment by AnneTee** [comment]
@kostajh I removed the link settings since they weren't working - I can add them back in if you want.
